site_name: deskit
site_url: https://TikaaVo.github.io/deskit
repo_url: https://github.com/TikaaVo/deskit
theme:
  name: material

nav:
  - Home: index.md
  - Algorithms:
    - DEWS-U: algorithms/dewsu.md
    - DEWS-I: algorithms/dewsi.md
    - DEWS-T: algorithms/dewst.md
    - DEWS-V: algorithms/dewsv.md
    - DEWS-IV: algorithms/dewsiv.md
    - LWSE-U: algorithms/lwseu.md
    - LWSE-I: algorithms/lwsei.md
    - KNORA-U: algorithms/knorau.md
    - KNORA-E: algorithms/knorae.md
    - KNORA-IU: algorithms/knoraiu.md
    - OLA: algorithms/ola.md
  - Backends:
    - KNN: backends/knn.md
    - FAISS: backends/faiss.md
    - Annoy: backends/annoy.md
    - HNSW: backends/hnsw.md
  - Algorithm Selection Guide: selection.md
  - Benchmark: benchmark.md