site_name: despy
site_url: https://TikaaVo.github.io/despy
repo_url: https://github.com/TikaaVo/despy
theme:
  name: material

nav:
  - Home: index.md
  - Algorithms:
    - KNN-DWS: algorithms/knndws.md
    - KNORA-U: algorithms/knorau.md
    - KNORA-E: algorithms/knorae.md
    - KNORA-IU: algorithms/knoraiu.md
    - OLA: algorithms/ola.md
  - ANN Backends: backends.md
  - Benchmark: benchmark.md